

import 'package:practice_demo_cwic/Models/currency_model.dart';

const List<String> nationality = const [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean"
];

List<String> cityList = [
  "Bristol",
  "Nottingham",
  "Newcastle",
  "Leicester",
  "Southampton",
  "Manchester",
];

List<CurrencyModel> currencyList = [
  CurrencyModel(currencycode: "GBP", currencysymbol: "£",countrycurrency: "Cornish (United Kingdom)"),
  CurrencyModel(currencycode: "AFN", currencysymbol: "؋", countrycurrency: "Afghanistan (Arabic)"),
  CurrencyModel(currencycode: "XAF", currencysymbol: "FCFA", countrycurrency: "Aghem (Cameroon)"),
  CurrencyModel(currencycode: "GHS", currencysymbol: "GH₵", countrycurrency: "Akan (Ghana)"),
  CurrencyModel(currencycode: "USD", currencysymbol: "\$", countrycurrency: "American Samoa"),
  CurrencyModel(currencycode: "EUR", currencysymbol: "€", countrycurrency: "Andorra"),
  CurrencyModel(currencycode: "AOA", currencysymbol: "Kz", countrycurrency: "Angola"),
  CurrencyModel(currencycode: "XCD", currencysymbol: "EC\$", countrycurrency: "Antigua and Barbuda"),
  CurrencyModel(currencycode: "DZD", currencysymbol: "د.ج.‏", countrycurrency: "Algeria"),
  CurrencyModel(currencycode: "ARS", currencysymbol: "\$", countrycurrency: "Argentina"),
  CurrencyModel(currencycode: "AMD", currencysymbol: "դր.", countrycurrency: "Armenian (Armenia)"),
  CurrencyModel(currencycode: "AWG", currencysymbol: "Afl.", countrycurrency: "Aruba"),
  CurrencyModel(currencycode: "INR", currencysymbol: "₹", countrycurrency: "Assamese (India)"),
  CurrencyModel(currencycode: "TZS", currencysymbol: "TSh", countrycurrency: "Asu (Tanzania)"),
  CurrencyModel(currencycode: "AUD", currencysymbol: "\$", countrycurrency: "Australia"),
  CurrencyModel(currencycode: "AZN", currencysymbol: "man.", countrycurrency: "Azerbaijan"),
  CurrencyModel(currencycode: "BSD", currencysymbol: "\$", countrycurrency: "Bahamas"),
  CurrencyModel(currencycode: "BHD", currencysymbol: "د.ب.‏", countrycurrency: "Bahrain"),
  CurrencyModel(currencycode: "XOF", currencysymbol: "CFA", countrycurrency: "Bambara (Mali)"),
  CurrencyModel(currencycode: "BDT", currencysymbol: "৳", countrycurrency: "Bangladesh"),
  CurrencyModel(currencycode: "BBD", currencysymbol: "\$", countrycurrency: "Barbados"),
  CurrencyModel(currencycode: "BYR", currencysymbol: "р.", countrycurrency: "Belarus"),
  CurrencyModel(currencycode: "BZD", currencysymbol: "\$", countrycurrency: "Belize"),
  CurrencyModel(currencycode: "ZMW", currencysymbol: "KR", countrycurrency: "Bemba (Zambia)"),
  CurrencyModel(currencycode: "BMD", currencysymbol: "\$", countrycurrency: "Barmuda"),
  CurrencyModel(currencycode: "BOB", currencysymbol: "Bs", countrycurrency: "Bolivia"),
  CurrencyModel(currencycode: "BAM", currencysymbol: "KM", countrycurrency: "Bosnia and Herzegovina"),
  CurrencyModel(currencycode: "BWP", currencysymbol: "P", countrycurrency: "Botswana"),
  CurrencyModel(currencycode: "BRL", currencysymbol: "R\$ ", countrycurrency: "Brazil"),
  CurrencyModel(currencycode: "BND", currencysymbol: "\$", countrycurrency: "Brunei"),
  CurrencyModel(currencycode: "BGN", currencysymbol: "лв.",countrycurrency: "Bulgarian (Bulgaria)"),
  CurrencyModel(currencycode: "BIF", currencysymbol: "FBu",countrycurrency: "Burundi"),
  CurrencyModel(currencycode: "CAD", currencysymbol: "\$",countrycurrency: "Canada"),
  CurrencyModel(currencycode: "CVE", currencysymbol: "CVE",countrycurrency: "Cape Verde"),
  CurrencyModel(currencycode: "KYD", currencysymbol: "\$",countrycurrency: "Cayman Islands"),
  CurrencyModel(currencycode: "MAD", currencysymbol: "MAD",countrycurrency: "Central Atlas Tamazight (Morocco)"),
  CurrencyModel(currencycode: "UGX", currencysymbol: "USh",countrycurrency: "Chiga (Uganda)"),
  CurrencyModel(currencycode: "CLP", currencysymbol: "\$",countrycurrency: "Chile"),
  CurrencyModel(currencycode: "CNY", currencysymbol: "￥",countrycurrency: "China"),
  CurrencyModel(currencycode: "COP", currencysymbol: "\$",countrycurrency: "Colombia"),
  CurrencyModel(currencycode: "KMF", currencysymbol: "ف.ج.ق.‏",countrycurrency: "Comoros"),
  CurrencyModel(currencycode: "CDF", currencysymbol: "FC",countrycurrency: "Congo - Kinshasa"),
  CurrencyModel(currencycode: "CRC", currencysymbol: "₡",countrycurrency: "Costa Rica"),
  CurrencyModel(currencycode: "HRK", currencysymbol: "kn",countrycurrency: "Croatia"),
  CurrencyModel(currencycode: "ANG", currencysymbol: "NAf.",countrycurrency: "Curacao"),
  CurrencyModel(currencycode: "CZK", currencysymbol: "Kč",countrycurrency: "Czech (Czech Republic)"),
  CurrencyModel(currencycode: "DKK", currencysymbol: "kr",countrycurrency: "Danish (Denmark)"),
  CurrencyModel(currencycode: "DJF", currencysymbol: "Fdj",countrycurrency: "Djibouti"),
  CurrencyModel(currencycode: "DOP", currencysymbol: "\$",countrycurrency: "Dominican Republic"),
  CurrencyModel(currencycode: "BTN", currencysymbol: "Nu.",countrycurrency: "Dzongkha (Bhutan)"),
  CurrencyModel(currencycode: "EGP", currencysymbol: "ج.م.‏",countrycurrency: "Egypt"),
  CurrencyModel(currencycode: "KES", currencysymbol: "Ksh",countrycurrency: "Embu (Kenya)"),
  CurrencyModel(currencycode: "ERN", currencysymbol: "Nfk",countrycurrency: "Eritrea"),
  CurrencyModel(currencycode: "ETB", currencysymbol: "Br",countrycurrency: "Ethiopia"),
  CurrencyModel(currencycode: "FJD", currencysymbol: "\$",countrycurrency: "Fiji"),
  CurrencyModel(currencycode: "PHP", currencysymbol: "₱",countrycurrency: "Filipino (Philippines)"),
  CurrencyModel(currencycode: "XPF", currencysymbol: "FCFP",countrycurrency: "French Polinesia"),
  CurrencyModel(currencycode: "GMD", currencysymbol: "D",countrycurrency: "Gambia"),
  CurrencyModel(currencycode: "GEL", currencysymbol: "GEL",countrycurrency: "Georgian (Georgia)"),
  CurrencyModel(currencycode: "GIP", currencysymbol: "£",countrycurrency: "Gibraltar"),
  CurrencyModel(currencycode: "GTQ", currencysymbol: "Q",countrycurrency: "Guatemala"),
  CurrencyModel(currencycode: "GNF", currencysymbol: "FG",countrycurrency: "Guinea"),
  CurrencyModel(currencycode: "GYD", currencysymbol: "\$",countrycurrency: "Guyana"),
  CurrencyModel(currencycode: "HTG", currencysymbol: "G",countrycurrency: "Haiti"),
  CurrencyModel(currencycode: "ILS", currencysymbol: "₪",countrycurrency: "Hebrew (Isreal)"),
  CurrencyModel(currencycode: "HKD", currencysymbol: "\$",countrycurrency: "Hong Kong SAR China"),
  CurrencyModel(currencycode: "HNL", currencysymbol: "L",countrycurrency: "Honduras"),
  CurrencyModel(currencycode: "HUF", currencysymbol: "Ft",countrycurrency: "Hungarian (Hungary)"),
  CurrencyModel(currencycode: "ISK", currencysymbol: "ISK",countrycurrency: "Iceland"),
  CurrencyModel(currencycode: "NGN", currencysymbol: "₦",countrycurrency: "Igbo (Nigeria)"),
  CurrencyModel(currencycode: "IDR", currencysymbol: "Rp",countrycurrency: "Indonesian (Indonesia)"),
  CurrencyModel(currencycode: "IQD", currencysymbol: "د.ع.‏",countrycurrency: "Iraq"),
  CurrencyModel(currencycode: "JMD", currencysymbol: "\$",countrycurrency: "Jamaica"),
  CurrencyModel(currencycode: "JPY", currencysymbol: "￥",countrycurrency: "Japanese (Japan)"),
  CurrencyModel(currencycode: "JOD", currencysymbol: "د.أ.‏",countrycurrency: "Jordan"),
  CurrencyModel(currencycode: "KGS", currencysymbol: "сом",countrycurrency: "Kyrgyzstan"),
  CurrencyModel(currencycode: "KZT", currencysymbol: "₸",countrycurrency: "Kazakh (Kazakhstan)"),
  CurrencyModel(currencycode: "RWF", currencysymbol: "RF",countrycurrency: "Kinyarwanda (Rwanda)"),
  CurrencyModel(currencycode: "KRW", currencysymbol: "₩",countrycurrency: "Korean (South Korea)"),
  CurrencyModel(currencycode: "KWD", currencysymbol: "د.ك.‏",countrycurrency: "Kuwait"),
  CurrencyModel(currencycode: "LAK", currencysymbol: "₭",countrycurrency: "Lao (Laos)"),
  CurrencyModel(currencycode: "LVL", currencysymbol: "LVL",countrycurrency: "Latvia"),
  CurrencyModel(currencycode: "LBP", currencysymbol: "ل.ل.‏",countrycurrency: "Lebanon"),
  CurrencyModel(currencycode: "ZAR", currencysymbol: "R",countrycurrency: "Lesotho"),
  CurrencyModel(currencycode: "LRD", currencysymbol: "\$",countrycurrency: "Liberia"),
  CurrencyModel(currencycode: "CHF", currencysymbol: "CHF",countrycurrency: "Liechtenstein"),
  CurrencyModel(currencycode: "LTL", currencysymbol: "LTL",countrycurrency: "Lithuania"),
  CurrencyModel(currencycode: "LYD", currencysymbol: "د.ل.‏",countrycurrency: "Libya"),
  CurrencyModel(currencycode: "MOP", currencysymbol: "MOP\$",countrycurrency: "Macau SAR China"),
  CurrencyModel(currencycode: "MKD", currencysymbol: "ден",countrycurrency: "Macedonia"),
  CurrencyModel(currencycode: "MGA", currencysymbol: "Ar",countrycurrency: "Madagascar"),
  CurrencyModel(currencycode: "MZN", currencysymbol: "MTn",countrycurrency: "Makhuwa-Meetto (Mozambique)"),
  CurrencyModel(currencycode: "MYR", currencysymbol: "RM",countrycurrency: "Malaysiya"),
  CurrencyModel(currencycode: "MWK", currencysymbol: "MK",countrycurrency: "Malawi"),
  CurrencyModel(currencycode: "MDL", currencysymbol: "MDL",countrycurrency: "Moldova"),
  CurrencyModel(currencycode: "MUR", currencysymbol: "Rs",countrycurrency: "Mauritius"),
  CurrencyModel(currencycode: "MRO", currencysymbol: "أ.م.‏",countrycurrency: "Mauritania"),
  CurrencyModel(currencycode: "MXN", currencysymbol: "\$",countrycurrency: "Mexico"),
  CurrencyModel(currencycode: "MNT", currencysymbol: "₮",countrycurrency: "Mongolian (Mongolia)"),
  CurrencyModel(currencycode: "NAD", currencysymbol: "\$",countrycurrency: "Nama (Namibia)"),
  CurrencyModel(currencycode: "NPR", currencysymbol: "नेरू",countrycurrency: "Nepal"),
  CurrencyModel(currencycode: "NZD", currencysymbol: "\$",countrycurrency: "New Zealand"),
  CurrencyModel(currencycode: "NIO", currencysymbol: "C\$",countrycurrency: "Nicaragua"),
  CurrencyModel(currencycode: "NOK", currencysymbol: "NOK",countrycurrency: "Norway"),
  CurrencyModel(currencycode: "OMR", currencysymbol: "ر.ع.‏",countrycurrency: "Oman"),
  CurrencyModel(currencycode: "PKR", currencysymbol: "Rs",countrycurrency: "Pakistan"),
  CurrencyModel(currencycode: "PAB", currencysymbol: "B\/.",countrycurrency: "Pananma"),
  CurrencyModel(currencycode: "PGK", currencysymbol: "K",countrycurrency: "Papua New Guinea"),
  CurrencyModel(currencycode: "PYG", currencysymbol: "₲",countrycurrency: "Paraguay"),
  CurrencyModel(currencycode: "PEN", currencysymbol: "S\/.",countrycurrency: "Peru"),
  CurrencyModel(currencycode: "PLN", currencysymbol: "PLN",countrycurrency: "Poland"),
  CurrencyModel(currencycode: "QAR", currencysymbol: "ر.ق.‏",countrycurrency: "Qatar"),
  CurrencyModel(currencycode: "RON", currencysymbol: "RON",countrycurrency: "Romania"),
  CurrencyModel(currencycode: "RUB", currencysymbol: "руб.",countrycurrency: "Russia"),
  CurrencyModel(currencycode: "WST", currencysymbol: "WS\$",countrycurrency: "Samoa"),
  CurrencyModel(currencycode: "STD", currencysymbol: "Db",countrycurrency: "Sao Tome and Principe"),
  CurrencyModel(currencycode: "SAR", currencysymbol: "ر.س.‏",countrycurrency: "Saudi Arabia"),
  CurrencyModel(currencycode: "RSD", currencysymbol: "дин.",countrycurrency: "Serbia"),
  CurrencyModel(currencycode: "SCR", currencysymbol: "SR",countrycurrency: "Seychelles"),
  CurrencyModel(currencycode: "SOS", currencysymbol: "S",countrycurrency: "Somalia"),
  CurrencyModel(currencycode: "SLL", currencysymbol: "Le",countrycurrency: "Sierra Leone"),
  CurrencyModel(currencycode: "SGD", currencysymbol: "\$",countrycurrency: "Singapore"),
  CurrencyModel(currencycode: "LKR", currencysymbol: "රු.",countrycurrency: "Sinhala (Sri Lanka)"),
  CurrencyModel(currencycode: "SBD", currencysymbol: "\$",countrycurrency: "Soloman Islands"),
  CurrencyModel(currencycode: "SSP", currencysymbol: "£",countrycurrency: "South Sudan"),
  CurrencyModel(currencycode: "SRD", currencysymbol: "\$",countrycurrency: "Suriname"),
  CurrencyModel(currencycode: "SZL", currencysymbol: "E",countrycurrency: "Swaziland"),
  CurrencyModel(currencycode: "SEK", currencysymbol: "SEK",countrycurrency: "Sweden"),
  CurrencyModel(currencycode: "TJS", currencysymbol: "сом",countrycurrency: "Tajik (Tazikistan)"),
  CurrencyModel(currencycode: "THB", currencysymbol: "฿",countrycurrency: "Thai (Thailand)"),
  CurrencyModel(currencycode: "TOP", currencysymbol: "T\$",countrycurrency: "Tonga"),
  CurrencyModel(currencycode: "TTD", currencysymbol: "\$",countrycurrency: "Trinidad and Tobago"),
  CurrencyModel(currencycode: "TND", currencysymbol: "د.ت.",countrycurrency: "Tunisia"),
  CurrencyModel(currencycode: "TRY", currencysymbol: "TRY",countrycurrency: "Turkey"),
  CurrencyModel(currencycode: "TMT", currencysymbol: "m.",countrycurrency: "Turkmen (Turkmenistan)"),
  CurrencyModel(currencycode: "UAH", currencysymbol: "₴",countrycurrency: "Ukraine"),
  CurrencyModel(currencycode: "AED", currencysymbol: "د.إ.‏",countrycurrency: "United Arab Emirates"),
  CurrencyModel(currencycode: "UYU", currencysymbol: "\$",countrycurrency: "Uruguay"),
  CurrencyModel(currencycode: "UZS", currencysymbol: "сўм",countrycurrency: "Uzbekistan"),
  CurrencyModel(currencycode: "VUV", currencysymbol: "VT",countrycurrency: "Vanuatu"),
  CurrencyModel(currencycode: "VEF", currencysymbol: "Bs.",countrycurrency: "Venezuela"),
  CurrencyModel(currencycode: "VND", currencysymbol: "₫",countrycurrency: "Vietnamese (vietnam)"),
  CurrencyModel(currencycode: "YER", currencysymbol: "ر.ي.‏",countrycurrency: "Yemen"),
];